theme: default
title: NEH Institute materials
description: July 2017
baseurl: /docs

navigation:
- text: Home
  url: index.html
- text: About
  url: about.html
- text: Blog
  url: blog.html
- text: Portfolio
  url: portfolio.html
